import pytest

PYTEST_INTEGRATION_MARKER = pytest.mark.integration
PYTEST_DEPENDENT_MARKER = pytest.mark.dependent
PYTEST_MANUAL_MARKER = pytest.mark.manual

PYTEST_INTEGRATION_TEST_MARKERS = [
    PYTEST_INTEGRATION_MARKER,
    PYTEST_DEPENDENT_MARKER,
    PYTEST_MANUAL_MARKER,
]

PYTEST_MANUAL_MARKERS = [
    PYTEST_INTEGRATION_MARKER,
    PYTEST_DEPENDENT_MARKER,
    PYTEST_MANUAL_MARKER,
]
