import pytest

PYTEST_SLOW_MARKER = pytest.mark.slow
PYTEST_NONDETERMINISTIC_MARKER = pytest.mark.nondeterministic
PYTEST_UNMITIGATED_SIDE_EFFECTS_MARKER = pytest.mark.unmitigated_side_effects

PYTEST_INTEGRATION_TEST_MARKERS = [
    PYTEST_SLOW_MARKER,
    PYTEST_NONDETERMINISTIC_MARKER,
    PYTEST_UNMITIGATED_SIDE_EFFECTS_MARKER,
]

PYTEST_MANUAL_MARKERS = [
    PYTEST_SLOW_MARKER,
    PYTEST_NONDETERMINISTIC_MARKER,
    PYTEST_UNMITIGATED_SIDE_EFFECTS_MARKER,
]
